spring:
  profiles:
    group:
      "local": "local,common"
---
spring:
  profiles:
    group:
      "prod": "prod,common"
---
spring:
  config:
    activate:
      on-profile: "prod"

---
spring:
  config:
    activate:
      on-profile: "local"

---
spring:
  config:
    activate:
      on-profile: "common"
server:
  port: 8081
